/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthc;

/**
 *
 * @author Indranil
 */
public class t_Solution extends javax.swing.JFrame {

    /**
     * Creates new form t_Solution
     */
    String city;
    public t_Solution() {
        initComponents();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doc_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        hosp_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hmebtn = new javax.swing.JButton();
        citycb = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        prevbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Help In Deed");

        doc_btn.setBackground(new java.awt.Color(0, 204, 204));
        doc_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doctor (1).png"))); // NOI18N
        doc_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        doc_btn.setBorderPainted(false);
        doc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_btnActionPerformed(evt);
            }
        });

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        hosp_btn.setBackground(new java.awt.Color(0, 204, 204));
        hosp_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hospital.png"))); // NOI18N
        hosp_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 4));
        hosp_btn.setBorderPainted(false);
        hosp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosp_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("hospitals");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("doctors");

        hmebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hme.png"))); // NOI18N
        hmebtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));
        hmebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmebtnActionPerformed(evt);
            }
        });

        citycb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jalandhar", "delhi", "ludhiana" }));
        citycb.setName(""); // NOI18N
        citycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citycbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("City");

        prevbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prevbtn.setText("Previous");
        prevbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(citycb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(prevbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doc_btn)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(hosp_btn))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hmebtn)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hmebtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(citycb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doc_btn)
                            .addComponent(hosp_btn))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addComponent(prevbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hosp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosp_btnActionPerformed
        // TODO add your handling code here:
        String city=(String)citycb.getSelectedItem();
        jTextArea.setText("\n"+city);
        switch(city)
        {
            case "jalandhar":
                
                jTextArea.setText("\n here list of some hospitals......"+"\n \nSGL Hospital(Garha Road, Guru Amardas Market, Jalandhar, Punjab, 144022)"
                        + "\n Sanjeevny Hospital(235,Scheme no3,Hoshiarpur Road, Phagwara, 144403)"+"\n\nJohal Multi-Speciality Hospital\n" +
"Address: Hoshiarpur Rd, Ladhewali Chowk, Rama Mandi, Jalandhar, Punjab 144005\n" +
"Hours: \n" +
"Open 24 hours\n" +
"Phone: 0181 503 3333\n"+"\n\nPatel Multi-Superspeciality Hospital - Best Hospital in Jalandhar | Best Robotic Surgeon in Jalandhar\n" +
"Address: Civil Lines, Jalandhar, Punjab 144001\n" +
"Hours: \n" +
"Open 24 hours \n" +
"Phone: 0181 204 1000\n"+"\n\n");
                break;
            case "ludhiana":
                 jTextArea.setText("\n here list of some hospitals......"+"\n \nKalra Hospital\n" +
"Address: Baba Than Singh Chowk, Shigar Cinema Road, Ludhiana, Punjab 141008\n" +
"Hours: \n" +
"Open 24 hours\n" +
"Phone: 098148 98000\n"+"\n\nFortis Hospital Ludhiana\n" +
"Address: Chandigarh Rd, near Radha Soami Satsang Bhavan, Village, Mundian Kalan, Ludhiana, Punjab 141010\n" +
"Hours: \n" +
"Open 24 hours \n" +
"Phone: 0161 522 2333\n" +
"\n\nSPS Hospital\n" +
"Address: Grand Trunk Rd, Sherpur Chowk, Sherpur, Ludhiana, Punjab 141001\n" +
"Hours: \n" +
"Open 24 hours\n" +
"Phone: 0161 661 7111");
                break;
            case "delhi":
                 jTextArea.setText("\n here list of some hospitals......"+"\n \nApollo Spectra Hospitals\n" +
"Address: 66A/2, New Rohtak Road, Block 23 B, Block 2C, Karol Bagh, New Delhi, Delhi 110005\n" +
"Hours: \n" +
"Open 24 hours\n" +
"Phone: 011 4004 3300\n" +
"\n\nIndraprastha Apollo Hospital\n" +
"Address: Chennai - Delhi Highway, Mathura Rd, Sarita Vihar, New Delhi, Delhi 110076\n" +
"Hours: \n" +
"Open 24 hours \n" +
"Phone: 1860 500 1066\n" +
"\n\nDharamshila Narayana Superspeciality Hospital\n" +
"Address: Metro Station, Dharamshila marg, Vasundhara Enclave Near Ashok Nagar, Dallupura, New Delhi, Delhi 110096\n" +
"Hours: \n" +
"Open 24 hours\n" +
"Phone: 080675 06880");
                break;
            default:
                 jTextArea.setText("\n \\n\n COME AGAIN");
                
        }
                
    }//GEN-LAST:event_hosp_btnActionPerformed

    private void hmebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmebtnActionPerformed
        // TODO add your handling code here:
        dashboard db=new dashboard();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_hmebtnActionPerformed

    private void doc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_btnActionPerformed
        // TODO add your handling code here:
        String city=(String)citycb.getSelectedItem();
        jTextArea.setText("\n"+city);
        switch(city)
        {
            case "jalandhar":
                
                jTextArea.setText("\n here list of some doctors......"+"\n \nDr. K K Guglani\n" +
                                  "Address: 59, Market Banda Bahadur Nagar, Mahvir Marg, India, Jalandhar, Punjab 144001\n" +
                                  "Hours: \n" +
                                  "Closes soon: 8:30PM ⋅ Opens 9:30AM Sun"+"\n \nDr..Dinesh Dada & Dr.Madhu Dada\n" +
                                   "Address: Dada hospital, Pathankot Rd, near Balle Balle farms, Chowk, Jalandhar\n" +
                                   "Hours: \n" +
                                   "Open ⋅ Closes 5AM Sun\n" +
                                   "Phone: 0181 260 3444"+"\n\nDr. K K Guglani\n" +
                                   "Address: 59, Market Banda Bahadur Nagar, Mahvir Marg, India, Jalandhar, Punjab 144001\n" +
                                   "Hours: \n" +
                                   "Closes soon: 8:30PM ⋅ Opens 9:30AM Sun\n" +
                                   "Phone: 0181 262 3624");
                break;
            case "ludhiana":
                 jTextArea.setText("\n here list of some doctors......"+"\n\nDr. K K Guglani\n" +
"Address: 59, Market Banda Bahadur Nagar, Mahvir Marg, India, Jalandhar, Punjab 144001\n" +
"Hours: \n" +
"Closes soon: 8:30PM ⋅ Opens 9:30AM Sun\n" +
"Phone: 0181 262 3624"+"\n\nDr. Harmeet Singh Saluja\n" +
"Address: 3129, Street Number 6, Gurdev Nagar, Ludhiana, Punjab 141001\n" +
"Hours: \n" +
"Closed ⋅ Opens 9AM Mon\n" +

"Phone: 098148 13575"+"\n\nDr US Sidhu Clinic\n" +
"Address: 82A, Malhar Cinema Rd, A - Block, E-Block, Sarabha Nagar, Ludhiana, Punjab 141001\n" +
"Hours: \n" +
"Closed ⋅ Opens 8:30AM Mon\n" +
"Phone: 0161 245 0340"+"\n\nDr Rajat Bhatia (ENT Specialist )\n" +
"Address: Opp. Old D.M.C, Dandi Swami Rd, Civil Lines, Ludhiana, Punjab 141001\n" +
"Hours: \n" +
"Closes soon: 9PM ⋅ Opens 12AM Sun\n" +
"Phone: 096460 36009"
);
                break;
            case "delhi":
                 jTextArea.setText("\n here list of some doctors......"+"\n\nDr. Harmeet Singh Rai, Best Emergency Physician in Delhi\n" +
"Address: Moolchand Hospital, Lajpat Nagar III, New Delhi, Delhi 110024\n" +
"Phone: 011 4200 0401"+"\n\nDr Palash Gupta\n" +
"Address: 190,Pocket-d 14, Sector 7, Opposite metro pillar no. 415, Rohini, New Delhi, Delhi 110085\n" +
"Hours: \n" +
"Closes soon: 8:30PM ⋅ Opens 5:30PM Mon\n"+"Phone: 098101 43845"+"\n\nDr Shashi Gupta\n" +
"Address: B-5/6, Pocket 4, Sector 4, Rohini, New Delhi, Delhi 110085\n" +
"\nPhone: 098104 76811");
                break;
            default:
                 jTextArea.setText("\n \n\n COME AGAIN");
                 break;
                
        }
    }//GEN-LAST:event_doc_btnActionPerformed

    private void citycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citycbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citycbActionPerformed

    private void prevbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevbtnActionPerformed
        // TODO add your handling code here:
        t_help hlp=new t_help();
        hlp.setVisible(true);
        dispose();
    }//GEN-LAST:event_prevbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(t_Solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(t_Solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(t_Solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(t_Solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new t_Solution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox citycb;
    private javax.swing.JButton doc_btn;
    private javax.swing.JButton hmebtn;
    private javax.swing.JButton hosp_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea;
    private javax.swing.JButton prevbtn;
    // End of variables declaration//GEN-END:variables
}
